### ISSUE TITLE
Chex 1.86 and TF Keras

### ISSUE THREAD

**Issue by camtice** [SoyGema/MARL-Melting-pot#7]
**Runs without Error**

```
git clone <this-repo>
cd <repo-home>
conda create -n mpc_main python=3.10
conda activate mpc_main
SYSTEM_VERSION_COMPAT=0 pip install dmlab2d

```

**First Error**
`pip install -e .`

ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.1 (from dm-meltingpot) (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1)
ERROR: No matching distribution found for tensorflow==2.11.1

**First Fix**
In setup.py line 121 'tensorflow==2.11.1', to 'tensorflow>=2.13.0',

**Second Error**
`sh ray_patch.sh`

ERROR: Attempting to patch Failed to import TF-Keras. Please note that TF-Keras is not installed by default when you install TensorFlow Probability. This is so that JAX-only users do not have to install TensorFlow or TF-Keras. To use TensorFlow Probability with TensorFlow, please install the tf-keras or tf-keras-nightly package. This can be be done through installing the tensorflow-probability[tf] extra. /Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/policy/sample_batch.py

**Fix**
`pip install 'tensorflow-probability[tf]'`

**Third Error**
`python baselines/train/run_ray_train.py`

Traceback (most recent call last):
  File "/Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot/baselines/train/run_ray_train.py", line 10, in <module>
    from configs import get_experiment_config
  File "/Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot/baselines/train/configs.py", line 1, in <module>
    from meltingpot import substrate
  ...
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/chex/_src/pytypes.py", line 54, in <module>
    PRNGKey = jax.random.KeyArray
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

**Fix**
setup.py line 109 'chex<0.1.81', to 'chex==0.1.86'

**Unresolved Error**
`python baselines/train/run_ray_train.py --num_workers 4 --num_gpus 0 --local --no-tune --algo ppo --framework torch --exp clean_up --seed 42 --results_dir my_results --logging INFO --wandb False --downsample 8`

ValueError: No default encoder config for obs space=Dict('COLLECTIVE_REWARD': Box(-inf, inf, (), float64), 'READY_TO_SHOOT': Box(-inf, inf, (), float64), 'RGB': Box(0, 255, (11, 11, 3), uint8)), lstm=False and attention=False found.

**Full Traceback for Final Error**
`(mpc_main) camerontice@Camerons-Laptop MARL-Melting-pot % python baselines/train/run_ray_train.py --num_workers 4 --num_gpus 0 --local --no-tune --algo ppo --framework torch --exp clean_up --seed 42 --results_dir my_results --logging INFO --wandb False --downsample 8`

2024-04-22 11:42:51,127 WARNING deprecation.py:50 -- DeprecationWarning: `DirectStepOptimizer` has been deprecated. This will raise an error in the future!
2024-04-22 11:42:51,370 - DEBUG - Popen(['git', 'version'], cwd=/Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot, stdin=None, shell=False, universal_newlines=False)
2024-04-22 11:42:51,383 - DEBUG - Popen(['git', 'version'], cwd=/Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot, stdin=None, shell=False, universal_newlines=False)
2024-04-22 11:42:51,398 - DEBUG - Trying paths: ['/Users/camerontice/.docker/config.json', '/Users/camerontice/.dockercfg']
2024-04-22 11:42:51,398 - DEBUG - Found file at path: /Users/camerontice/.docker/config.json
2024-04-22 11:42:51,398 - DEBUG - Found 'credsStore' section
2024-04-22 11:42:51,432 - DEBUG - [Tracing] Create new propagation context: {'trace_id': '22b069ba99ac4023be6cf6fd3f7f1aaa', 'span_id': '93f5b62e623a58dd', 'parent_span_id': None, 'dynamic_sampling_context': None}
Running trails with the following arguments:  Namespace(num_workers=4, num_gpus=0, local=True, no_tune=True, algo='ppo', framework='torch', exp='clean_up', seed=42, results_dir='my_results', logging='INFO', wandb=True, downsample=True, as_test=False)
2024-04-22 11:42:51,484 - DEBUG - Attempting to acquire lock 14508453040 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453040 acquired on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to release lock 14508453040 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453040 released on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to acquire lock 14508453568 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453568 acquired on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to release lock 14508453568 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453568 released on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to acquire lock 14508453040 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453040 acquired on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to release lock 14508453040 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508453040 released on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Attempting to acquire lock 14508450928 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,485 - DEBUG - Lock 14508450928 acquired on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,486 - DEBUG - Attempting to release lock 14508450928 on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
2024-04-22 11:42:51,486 - DEBUG - Lock 14508450928 released on /tmp/ray/session_2024-04-22_11-42-51_484519_88590/ports_by_node.json.lock
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
2024-04-22 11:42:53,056 INFO worker.py:1612 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
2024-04-22 11:42:53,398 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
The selected option is not tested. You may encounter issues if you use the baseline            policy configurations with non-tested algorithms
WARNING! No wandb API key found, running without wandb!
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/air/config.py:803: UserWarning: Setting a `RunConfig.local_dir` is deprecated and will be removed in the future. If you are not using remote storage,set the `RunConfig.storage_path` instead. Otherwise, set the`RAY_AIR_LOCAL_CACHE_DIR` environment variable to control the local cache location.
  warnings.warn(
2024-04-22 11:42:53,628 INFO tune.py:666 -- [output] This will use the new output engine with verbosity 0. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
2024-04-22 11:42:53,637 WARNING deprecation.py:50 -- DeprecationWarning: `build_tf_policy` has been deprecated. This will raise an error in the future!
2024-04-22 11:42:53,639 WARNING deprecation.py:50 -- DeprecationWarning: `build_policy_class` has been deprecated. This will raise an error in the future!
2024-04-22 11:42:53,656 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/gymnasium/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:141: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:165: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
2024-04-22 11:42:53,680 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
╭────────────────────────────────────────────────────────╮
│ Configuration for experiment     clean_up              │
├────────────────────────────────────────────────────────┤
│ Search algorithm                 BasicVariantGenerator │
│ Scheduler                        FIFOScheduler         │
│ Number of trials                 1                     │
╰────────────────────────────────────────────────────────╯

View detailed results here: /Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot/my_results/torch/clean_up
To visualize your results with TensorBoard, run: `tensorboard --logdir /Users/camerontice/Desktop/meltingpot/test2/MARL-Melting-pot/my_results/torch/clean_up`

2024-04-22 11:42:53,799 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
:job_id:01000000
:job_id:01000000
2024-04-22 11:42:53,824 WARNING worker.py:854 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
:task_name:bundle_reservation_check_func
:task_name:bundle_reservation_check_func
:actor_name:PPO
:actor_name:PPO
2024-04-22 11:42:53,841 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
2024-04-22 11:42:53,841 WARNING algorithm_config.py:656 -- Cannot create PPOConfig from given `config_dict`! Property __stdout_file__ not supported.
:actor_name:RolloutWorker
:actor_name:RolloutWorker
/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/gymnasium/spaces/box.py:227: UserWarning: WARN: Casting input x to numpy array.
  logger.warn("Casting input x to numpy array.")
2024-04-22 11:42:54,995 WARNING algorithm_config.py:2534 -- Setting `exploration_config={}` because you set `_enable_rl_module_api=True`. When RLModule API are enabled, exploration_config can not be set. If you want to implement custom exploration behaviour, please modify the `forward_exploration` method of the RLModule at hand. On configs that have a default exploration config, this must be done with `config.exploration_config={}`.
[2024-04-22 11:42:54,999 E 88590 9807680] core_worker.cc:1705: Pushed Error with JobID: 01000000 of type: task with message: ray::RolloutWorker.__init__() (pid=88590, ip=127.0.0.1, actor_id=cbf960f61968bb00ce1891d601000000, repr=<ray.rllib.evaluation.rollout_worker._modify_class.<locals>.Class object at 0x3e6436c80>)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 525, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1727, in _update_policy_map
    self._build_policy_map(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1838, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 142, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 49, in __init__
    TorchPolicyV2.__init__(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 92, in __init__
    model = self.make_rl_module()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 424, in make_rl_module
    marl_module = marl_spec.build()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 462, in build
    module = self.marl_module_class(module_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 58, in __init__
    super().__init__(config or MultiAgentRLModuleConfig())
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 307, in __init__
    self.setup()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 65, in setup
    self._rl_modules[module_id] = module_spec.build()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 104, in build
    module = self.module_class(module_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/torch/torch_rl_module.py", line 82, in __init__
    RLModule.__init__(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 307, in __init__
    self.setup()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_rl_module.py", line 20, in setup
    catalog = self.config.get_catalog()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 189, in get_catalog
    return self.catalog_class(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_catalog.py", line 67, in __init__
    super().__init__(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 106, in __init__
    self.__post_init__()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 135, in __post_init__
    self.encoder_config = self.get_encoder_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 249, in get_encoder_config
    tokenizer_config=cls.get_tokenizer_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 333, in get_tokenizer_config
    return cls.get_encoder_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 307, in get_encoder_config
    raise ValueError(
ValueError: No default encoder config for obs space=Dict('COLLECTIVE_REWARD': Box(-inf, inf, (), float64), 'READY_TO_SHOOT': Box(-inf, inf, (), float64), 'RGB': Box(0, 255, (11, 11, 3), uint8)), lstm=False and attention=False found. at time: 1.7138e+09
2024-04-22 11:42:54,999 ERROR actor.py:970 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=88590, ip=127.0.0.1, actor_id=cbf960f61968bb00ce1891d601000000, repr=<ray.rllib.evaluation.rollout_worker._modify_class.<locals>.Class object at 0x3e6436c80>)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 525, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1727, in _update_policy_map
    self._build_policy_map(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1838, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 142, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 49, in __init__
    TorchPolicyV2.__init__(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 92, in __init__
    model = self.make_rl_module()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 424, in make_rl_module
    marl_module = marl_spec.build()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 462, in build
    module = self.marl_module_class(module_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 58, in __init__
    super().__init__(config or MultiAgentRLModuleConfig())
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 307, in __init__
    self.setup()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/marl_module.py", line 65, in setup
    self._rl_modules[module_id] = module_spec.build()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 104, in build
    module = self.module_class(module_config)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 315, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/torch/torch_rl_module.py", line 82, in __init__
    RLModule.__init__(self, *args, **kwargs)
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 307, in __init__
    self.setup()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_rl_module.py", line 20, in setup
    catalog = self.config.get_catalog()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/rl_module/rl_module.py", line 189, in get_catalog
    return self.catalog_class(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_catalog.py", line 67, in __init__
    super().__init__(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 106, in __init__
    self.__post_init__()
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 135, in __post_init__
    self.encoder_config = self.get_encoder_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 249, in get_encoder_config
    tokenizer_config=cls.get_tokenizer_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 333, in get_tokenizer_config
    return cls.get_encoder_config(
  File "/Users/camerontice/miniconda3/envs/mpc_main/lib/python3.10/site-packages/ray/rllib/core/models/catalog.py", line 307, in get_encoder_config
    raise ValueError(
ValueError: No default encoder config for obs space=Dict('COLLECTIVE_REWARD': Box(-inf, inf, (), float64), 'READY_TO_SHOOT': Box(-inf, inf, (), float64), 'RGB': Box(0, 255, (11, 11, 3), uint8)), lstm=False and attention=False found.

**Comment by SoyGema** [comment]
Hey @camtice I had the opportunity to check this with @whymath .
We are investigating this issue, but we where able to train locally on mac :

1.Here you have a pip freeze . We checked ray and jax versions

```
absl-py==2.1.0
aiohttp==3.9.3
aiohttp-cors==0.7.0
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.3.0
appdirs==1.4.4
astunparse==1.6.3
async-timeout==4.0.3
attrs==23.2.0
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
chex==0.1.86
click==8.1.7
cloudpickle==3.0.0
colorful==0.5.6
contextlib2==21.6.0
distlib==0.3.8
dm-env==1.6
dm-meltingpot==2.1.1.dev10
dm-tree==0.1.8
dmlab2d==1.0.0
docker-pycreds==0.4.0
e==1.4.5
exceptiongroup==1.2.0
Farama-Notifications==0.0.4
fastapi==0.110.0
filelock==3.13.1
flatbuffers==24.3.7
frozenlist==1.4.1
fsspec==2024.3.1
gast==0.5.4
gitdb==4.0.11
GitPython==3.1.42
google-api-core==2.18.0
google-auth==2.29.0
google-pasta==0.2.0
googleapis-common-protos==1.63.0
grpcio==1.62.1
gymnasium==0.29.1
h11==0.14.0
h5py==3.10.0
httptools==0.6.1
idna==3.6
immutabledict==4.2.0
importlib_metadata==7.1.0
jax==0.4.25
jaxlib==0.4.25
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
keras==3.1.1
libclang==18.1.1
lz4==4.3.3
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
ml-dtypes==0.3.2
ml_collections==0.1.1
mpmath==1.3.0
msgpack==1.0.8
```
2. Please check the README.md file in this section, as we think this might be related to ray
[Identified issues with ray](https://github.com/rstrivedi/Melting-Pot-Contest-2023/tree/main?tab=readme-ov-file#identified-issues-with-ray-261) . Let you know that I was able to run this with torch.
What I did is downloaded the ray project folder **Manually** and change line 181 as you can see in the README

`self.num_outputs = concat_size if not self.post_fc_stack else self.post_fc_stack.num_outputs`

I can say that changing this line made it work for me.
LMK how this goes. We might gather on Wednesday afternoon CET time , in case you need a call
